export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const POST_PRODUCTS = "POST_PRODUCTS";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
export const POST_USERS = "POST_USERS";
export const GET_USERS = "GET_USERS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_REVIEWS = "GET_REVIEWS";
export const FILTER_REVIEWS = "FILTER_REVIEWS";
export const POST_REVIEW = "POST_REVIEW";
export const DELETE_REVIEW= "DELETE_REVIEW";
export const PUT_ADMIN_USER = "PUT_ADMIN_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const DELETE_ITEM_CARRITO = "DELETE_ITEM_CARRITO";



